#cloud-config

packages:
  - docker.io=20.10.2-0ubuntu1~20.04.2
  - ansible=2.9.6+dfsg-1

users:
- name: omegasphinx
  uid: 2000
                 
     
    

write_files:
- path: /home/omegasphinx/.ssh/omegasphinx_github_rsa
  permissions: 600
  owner: omegasphinx
  content: |
      -----BEGIN OPENSSH PRIVATE KEY-----
b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
NhAAAAAwEAAQAAAYEAtVGcrcGX3gmrYq55zkyZXJnrDmiSF9dMnroeklK8IJPo+GGO7cOH
b7hQVyFjFMYnqQ9J7DgPGrWCX2z/NPWPsrIvk7BSFCQfrkyCf/1EMQD3bNf26bbk3DR0Ws
JdPIzqHkEN0mekSbtE+vXHxOqIlN7RlhNY4BsmEww5/Xa60W+22mznb38P4bsGo8U2kIuw
/rbab/AY6CCTvbzJv/SV8ybRz0B98YP/pB8B7XuVdpTVZpDwRPcLjDaz5XUKrfrRosN6jo
+8sL7uKe8woZf0K5Eb+HQPKU3WEYclLORBztqAR41bcOJlQKN2F/W1NThj6fkBSL7SAZ1X
cAOQ8bNb0WCIBxq4PU+5QAcBh5+6WW6xASDpIp/GEzZ1zj6MtqYes2RVBGhK03+FN1gY6+
zZW2/HKJgolp8wH6nFUZVI+GwcyVxShlgC20L25dyYwd5eQqvddfPIRQeuHO3qi6sMMkD+
p8T9Czo1lsDE4pUOlfoJWBGMthAMD46bAVGK6d05AAAFmPmYeOH5mHjhAAAAB3NzaC1yc2
EAAAGBALVRnK3Bl94Jq2Kuec5MmVyZ6w5okhfXTJ66HpJSvCCT6Phhju3Dh2+4UFchYxTG
J6kPSew4Dxq1gl9s/zT1j7KyL5OwUhQkH65Mgn/9RDEA92zX9um25Nw0dFrCXTyM6h5BDd
JnpEm7RPr1x8TqiJTe0ZYTWOAbJhMMOf12utFvttps529/D+G7BqPFNpCLsP622m/wGOgg
k728yb/0lfMm0c9AffGD/6QfAe17lXaU1WaQ8ET3C4w2s+V1Cq360aLDeo6PvLC+7invMK
GX9CuRG/h0DylN1hGHJSzkQc7agEeNW3DiZUCjdhf1tTU4Y+n5AUi+0gGdV3ADkPGzW9Fg
iAcauD1PuUAHAYefullusQEg6SKfxhM2dc4+jLamHrNkVQRoStN/hTdYGOvs2VtvxyiYKJ
afMB+pxVGVSPhsHMlcUoZYAttC9uXcmMHeXkKr3XXzyEUHrhzt6ourDDJA/qfE/Qs6NZbA
xOKVDpX6CVgRjLYQDA+OmwFRiundOQAAAAMBAAEAAAGADkgRWTZIafrE/w7TFUa/RaXx97
6Q00PoCxCJ2+icXMyJqxa0FVIzVr9jxJkinr5E3XIQ1oRL3ESzsiR5rYgx+1dBnBZlQKTf
wfDQzpf6SQnUc0RHdH0tZZLUH1nz0hMfVaa2Gf6D2DLh6gp147K9c0xhobqAY5Z/1zw9TR
OO/3QXKPku+X8+lv8ONNQRyizWkhmA9xQoQhBe0rEOCwqOzQofuH1R7jYBasHuevAjA6YR
cPS1mBkFVdPxM3+WicGZo4UNLo0ycu5kOYBFvlBQRPx3aDJxfOEE5G4lLp8CfRh21gMzFh
UQBzTOjlzPjaianUmDAPIKGfR6RPZnOgtyzbE/vayYkpso1dF+Uw0KzvcDD4+b6YUm4f/J
bcBhigRDALMY4zbVQyDhGOGTnZmIqOek+JJ9HXHhe9Y2BF+Wk1o5ubGH7qrbVtsDKWdu1z
pp0HhQXjsujCWC7HFoLbh0CaPCjJDLyZkhKbL8ZUts2Y5Pfkr+CwHTCnbY8IMHHx0JAAAA
wQCn9pnpucua+oL1qwnptgXRID+Z+nfG5qzTkljR8ihOhdDfDP+ccA2Co1cs9xLdpb1L1T
9SyUBuHK6WQ3fuPdmwH0ui/emMQwWmoJNcJOJ2r0CTqEo6eC0vmdlQGdwPozl6n3pcQ6uk
p7WGS/PCXYwpTvSr8BHIhgmOiFGSXJuq2XlelfmTxaNAOb49K0F/t/8cURhkXwhoov8eI7
PV9xR/sD/6CE48T4Xy3r2gP2Zq/9GPRVPeiX7wpDXyoaqMV1YAAADBAONpb4Y+ho0F3PDc
5bYo+MFUt6d1Cuk8/bWUbyd2QcTvQdIg817QwcnYQuZ2Hsp6wVzBJYWtTRYmVwtLenztam
mAYU9kA50eNBUtTIRcTGF+5XArmqoHpQEVxoTSzv8jTFuFrpvxtjYER066S6riYVs0hLG1
psoECcd3egA3sckvTqX05dPTVRaG9xsF45BuRC7xLwjI8Tjema+gcpsK4ySINuAl8LSiiN
jAbwEHLcNirvtKEylTVBwcneesenHkJwAAAMEAzBzPcPCnTgioFzlo2EmounDw7gP91jV0
zanUCWM7pP/HaVIqtbgRWWSnLvNxABuNCJmK5wV3O3rCbgJecXdxy6eLPy+Al607uJJJK5
CBHHI5Vk5Nhbu3lCC2jOCEw58jbhUfspG75RZCSOSYoIAXRb78Os39r7GFFN0zFl6JDaw8
vDAY4AF0c/qvIhfccCkhxRFtiBG1D1Td+dVSsGuz6O8GpdTKKVFpwBOsD2MfKYUmW9zIgI
s44QCMjjC8pi+fAAAAImJyaWFuZGFudEBMeWRpYXMtTWFjQm9vay1Qcm8ubG9jYWw=
-----END OPENSSH PRIVATE KEY-----
 
  
- path: /etc/systemd/system/postgres.service
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=The postgres database
    Wants=gcr-online.target
    After=gcr-online.target

    [Service]
    Environment="HOME=/home/omegasphinx"
    ExecStartPre=/usr/bin/docker-credential-gcr configure-docker --registries gcr.io
    ExecStart=/usr/bin/docker run --rm --name=postgres gcr.io/dataexchange-redux-313019/dataexchange_production_postgres  
    ExecStop=/usr/bin/docker stop postgres 
    ExecStopPost=/usr/bin/docker rm postgres

- path: /etc/systemd/system/redis.service
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=The Redis container
    Wants=gcr-online.target
    After=gcr-online.target

    [Service]
    Environment="HOME=/home/omegasphinx"
    ExecStartPre=/usr/bin/docker-credential-gcr configure-docker --registries gcr.io
    ExecStart=/usr/bin/docker run --rm --name=redis gcr.io/dataexchange-redux-313019/redis:5.0  
    ExecStop=/usr/bin/docker stop redis 
    ExecStopPost=/usr/bin/docker rm redis

- path: /etc/systemd/system/django.service
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=The Django web app
    Wants=gcr-online.target
    After=gcr-online.target

    [Service]
    Environment="HOME=/home/omegasphinx"
    ExecStartPre=/usr/bin/docker-credential-gcr configure-docker --registries gcr.io
    ExecStart=/usr/bin/docker run --rm --name=django gcr.io/dataexchange-redux-313019/dataexchange_production_django  /start 
    ExecStop=/usr/bin/docker stop django 
    ExecStopPost=/usr/bin/docker rm django

- path: /etc/systemd/system/traefik.service
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=The web proxy
    Wants=gcr-online.target
    After=gcr-online.target

    [Service]
    Environment="HOME=/home/omegasphinx"
    ExecStartPre=/usr/bin/docker-credential-gcr configure-docker --registries gcr.io
    ExecStart=/usr/bin/docker run --rm --name=traefik gcr.io/dataexchange-redux-313019/dataexchange_production_traefik  
    ExecStop=/usr/bin/docker stop traefik 
    ExecStopPost=/usr/bin/docker rm traefik

- path: /etc/systemd/system/celeryworker.service
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=The Celery worker
    Wants=gcr-online.target
    After=gcr-online.target

    [Service]
    Environment="HOME=/home/omegasphinx"
    ExecStartPre=/usr/bin/docker-credential-gcr configure-docker --registries gcr.io
    ExecStart=/usr/bin/docker run --rm --name=celeryworker gcr.io/dataexchange-redux-313019/dataexchange_production_celeryworker  /start-celeryworker 
    ExecStop=/usr/bin/docker stop celeryworker 
    ExecStopPost=/usr/bin/docker rm celeryworker

- path: /etc/systemd/system/celerybeat.service
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=The Celerybeat container
    Wants=gcr-online.target
    After=gcr-online.target

    [Service]
    Environment="HOME=/home/omegasphinx"
    ExecStartPre=/usr/bin/docker-credential-gcr configure-docker --registries gcr.io
    ExecStart=/usr/bin/docker run --rm --name=celerybeat gcr.io/dataexchange-redux-313019/dataexchange_production_celerybeat  /start-celerybeat 
    ExecStop=/usr/bin/docker stop celerybeat 
    ExecStopPost=/usr/bin/docker rm celerybeat

- path: /etc/systemd/system/celeryflower.service
  permissions: 0644
  owner: root
  content: |
    [Unit]
    Description=The Celery Flower container
    Wants=gcr-online.target
    After=gcr-online.target

    [Service]
    Environment="HOME=/home/omegasphinx"
    ExecStartPre=/usr/bin/docker-credential-gcr configure-docker --registries gcr.io
    ExecStart=/usr/bin/docker run --rm --name=celeryflower gcr.io/dataexchange-redux-313019/dataexchange_production_flower  /start-flower 
    ExecStop=/usr/bin/docker stop celeryflower 
    ExecStopPost=/usr/bin/docker rm celeryflower


runcmd:
- systemctl daemon-reload
- systemctl start postgres.service
- systemctl start redis.service
- systemctl start django.service
- systemctl start traefik.service
- systemctl start celeryworker.service
- systemctl start celerybeat.service
- systemctl start celeryflower.service
