---
- name: Deploy application
  hosts: webservers
  remote_user: briandant

vars_files:
    - ansible_vars/base.yml
    - ansible_vars/{{ env }}.yml

  roles:
    - carlosbuenosvinos.ansistrano-deploy
