---
- name: Builds out the machine; use with Ansible Pull
  hosts: localhost

  vars:
    env: production

  vars_files:
    - "ansible_vars/base.yml"
    - "ansible_vars/{{ env }}.yml"

  tasks:
    - name: download docker-credential-gcr
      ansible.builtin.shell: "curl -fsSL {{ docker_credential_gcr__uri|quote }} | tar xz"
      args:
        creates: /usr/bin/docker-credential-gcr

    - name: make docker-credential-gcr executable
      ansible.builtin.file:
        path: /usr/bin/docker-credential-gcr
        owner: root
        mode: '0664'
