---
- name: Builds out the machine, user with Ansible Pull
  hosts: localhost

  vars:
    env: production

  vars_files:
    - "ansible_vars/base.yml"
    - "ansible_vars/{{ env }}.yml"

  tasks:
    - name: download docker-credential-gcr
      ansible.builtin.shell: >
        curl -fsSL {{ docker_credential_gcr__uri }} \
        | tar xz --to-stdout ./docker-credential-gcr \
        > /usr/bin/docker-credential-gcr && chmod +x /usr/bin/docker-credential-gcr

  roles:
    - fubarhouse.golang
