# Deploy user account #
gcp_deploy_user: omegasphinx
gcp_deploy_userid: 2000
gcp_deploy_service_account_email: "service-{{ gcp_deploy_user }}@{{ gcp_project }}.iam.gserviceaccount.com"
gcp_deploy_service_account_file: "{{ gcp_deploy_user }}-service-account_key.json"
gcp_deploy_user_scopes:
  - https://www.googleapis.com/auth/devstorage.read_only

gcp_project: dataexchange-redux-313019
gcp_project_number: 1073747879403
gcp_instance_name: dataexchange-ubuntu
gcp_region: us-west1
gcp_zone: us-west1-a

# Docker
gcp_docker_registry: gcr.io
gcp_registry_full_prefix: "{{ gcp_docker_registry }}/{{ gcp_project }}"

# vars for https://github.com/fubarhouse/ansible-role-golang
go_version: 1.16
go_install_clean: true
GOPATH: /home/{{ gcp_deploy_user }}/go
GOROOT: /usr/local/go
GOPROXY: https://proxy.golang.org
