server_domain: 'de.briandant.com'

gunicorn_workers: 3
application_vars_file: application_vars/production_env.j2
letsencrypt_cert_domains:
  - '{{ server_domain }}'

gcr_prefix: gcr.io/dataexchange-311421/

docker_login_keyfile_dir: /opt/docker/
docker_login_keyfile_path: /opt/docker/gcrkeyfile.json

