---
gcp_cred_kind: "serviceaccount"
gcp_docker_registry: gcr.io
gcp_project: dataexchange-redux-313019
# dataexchange-311421
gcp_project_number: 1073747879403
# 141784097243
gcp_registry_full_prefix: "{{ gcp_docker_registry }}/{{ gcp_project }}"
gcp_image_project: ubuntu-os-cloud
gcp_image_family: ubuntu-2004-lts
gcp_instance_name: dataexchange-ubuntu
gcp_instance_scopes:
  - default
# See machine types here: https://cloud.google.com/compute/docs/machine-types#n1_shared-core_machine_types
gcp_machine_type: g1-small
gcp_region: us-west1
gcp_zone: us-west1-a
# This key is tied to an account with "project owner" permissions.
# gcp_service_account_file: "dataexchange-311421-b1b8d9308172.json"

# APIs #
# The APIs need to be enabled on the project.
gcp_apis:
  - compute.googleapis.com
  - containerregistry.googleapis.com

# Default instance service account #
# A default account, with the following email, is created with all GCP projects
# and is tied closely to the instance and each instance can have only one
# service account.  It's therefore most easy and prudent to assign this as the
# *one* service account for the machine.  See:
# https://cloud.google.com/iam/docs/service-accounts#default
gcp_default_service_account: "{{ gcp_project_number}}-compute@developer.gserviceaccount.com"
gcp_default_service_account_scopes:
  - https://www.googleapis.com/auth/devstorage.read_only

# Machine-creating service account #
gcp_createmachine_user_name: alphasphinx
gcp_createmachine_user_email: "service-{{ gcp_createmachine_user_name }}@{{ gcp_project}}.iam.gserviceaccount.com"
gcp_createmachine_user_keyfile: "/tmp/{{ gcp_createmachine_user_name }}-service-account-key.json"
# See perms reference: https://cloud.google.com/iam/docs/permissions-reference
gcp_createmachine_user_roles:
  - roles/compute.instanceAdmin.v1
  - roles/compute.networkAdmin
  - roles/iam.serviceAccountUser
  - roles/compute.securityAdmin
