
#- name: Install base packages
  #  ansible.builtin.apt:
    #name: [build-essential, htop, git, libpq-dev, supervisor]
    #state: present
    #  tags: packages

- name: Set the motd
  copy: src=files/motd.txt dest=/etc/motd

- name: Set ssh keys to root user
  ansible.posix.authorized_key:
    user: root
    key: {{ lookup('file', 'ansible_vars/public_keys/root_user_keys') }}
    state: present
    exclusive: yes
    tags: environment
